MAX_PARALLEL_POSITIONS =10
POSITION_SIDE= 'LONG'
TOKEN_SUPPORTED = 'ETH'
TRADE_INTERVAL = 3600
VID_CURSOR =1

TRADE_FEATURES_URL = 'localhost:8000/v1/features'
MODEL_SERVER_URL = 'http://localhost:5000/predict'
FIX_LEVERAGE = 20